
############################################################
# Dockerfile to build Client container images
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM gcc

# File Author / Maintainer
MAINTAINER Ashish Kashinath

#Mounting the Volume
VOLUME ["/data"]

#Copy Requisite files from host to the container
ADD catclient.c .
ADD compilerscript_client.sh .
ADD compilerscript_client_backup.sh .

#Install Basic Stuff
RUN apt-get install -y gcc \ 
#echo -e "Basic Installation Over!\n\n" \
&& chmod +x compilerscript_client.sh \
&& chmod +x compilerscript_client_backup.sh

# Execute the catclient code
CMD ["./compilerscript_client_backup.sh"]

 


