
############################################################
# Dockerfile to build Server container images
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM gcc

# File Author / Maintainer
MAINTAINER Ashish Kashinath

#Mounting the Volume
VOLUME ["/data"]

#Copy Requisite files from host to the container
ADD catserver.c .
ADD compilerscript_server.sh .
ADD compilerscript_server_backup.sh .

#Install Basic Stuff
RUN apt-get install -y gcc \
#echo -e "Basic Installation Over!\n\n" \
&& chmod +x compilerscript_server.sh \
&& chmod +x compilerscript_server_backup.sh

# Execute the catserver code
CMD ["./compilerscript_server_backup.sh"]


