#!/bin/sh

############################################################
# Dockerfile to build Data Volume Container images
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Ashish Kashinath

#Mounting the Volume
VOLUME ["/data"]

#Copying strings.txt from host to the container
ADD string.txt /data/

#Install Basic Stuff
#RUN apt-get update && apt-get install -y vim
#&& echo -e "Basic Installation Over!\n\n"



